name: bmi_app
description: "bnltd_bmi_app"
publish_to: 'bnltd'
version: 1.0.3+4

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  package_info_plus: ^8.3.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/fonts/
    - assets/image/
  fonts:
    - family: exo2
      fonts:
        - asset: assets/fonts/exo2.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster.ttf
